version: '3'
services:
  db:
    image: postgres:10.6
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
  web:
    build: .
#    rubymine使わない場合は下記のコメントを外す
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails-app
    ports:
        - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD:
      DATABASE_HOST: db
