version: '3'
services:
  db:
    image: postgres:10.6
    container_name: db
    hostname: db
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
  rails:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    container_name: rails
    hostname: rails
    volumes:
      - .:/rails-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: example
      DATABASE_HOST: db
